/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import ds.Category;
import ds.Expense;
import ds.PersonalFinance;
import java.util.ArrayList;

/**
 *
 * @author Lenovo
 */
public class Catsar extends javax.swing.JFrame {
PersonalFinance a = null;
    
    public Catsar(PersonalFinance b) {
        a=b;
        initComponents();
        atnaujintilentele();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setTitle("Add Category");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"a", "a"},
                {"b", "d"}
            },
            new String [] {
                "Pavadinimas", "Aprasymas"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
public void atnaujintilentele(){
    ArrayList<Category> sar = a.getCategory();
    
    String [][] mas = new String [sar.size()][2];
    int i = 0;
    for(Category k:sar){
        mas[i][0] = k.getName();
        mas[i][1] = k.getDescription();
        i++;
    }
    jTable1.setModel(new javax.swing.table.DefaultTableModel(
            mas,
            new String [] {
                "Pavadinimas", "Aprasymas"
            }
        ));
}
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
