/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import static UI.JAVA3LAB.con;
import ds.PersonalFinance;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import static javafx.scene.AccessibleAttribute.COLUMN_INDEX;

/**
 *
 * @author Lenovo
 */
public class Catsar extends javax.swing.JFrame {
PersonalFinance a = null;
    
    public Catsar(PersonalFinance b) {
        a=b;
        initComponents();
        atnaujintilentele();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setTitle("Add Category");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"a", "a"},
                {"b", "d"}
            },
            new String [] {
                "Pavadinimas", "Aprasymas"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
public void atnaujintilentele(){
 
        try {
            
            String sql = "SELECT KATEGORIJOS, DESCR FROM APP.PS";
            ResultSet rsl = con.getback(sql);
            ResultSetMetaData rsmd = rsl.getMetaData();
           int columnsNumber = rsmd.getPrecision(WIDTH);
           // int columnsNumber = rsmd.getColumnCount(); // RANDOM OUT OF BOUNDS KAA ???
            String [][] mas = new String [columnsNumber][2];
            int i=0;
          
                while(rsl.next()) {
                    
                    mas[i][0]= rsl.getString("KATEGORIJOS");
                    mas[i][1]= rsl.getString("DESCR");
                    i++;
                }
          
            
            jTable1.setModel(new javax.swing.table.DefaultTableModel(
                    mas,
                    new String [] {
                        "Pavadinimas", "Aprasymas"
                    }
            ));
            
            
        }
        catch (SQLException ex) {
            Logger.getLogger(Catsar.class.getName()).log(Level.SEVERE, null, ex);
        }
    
   
}
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
