/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import static UI.JAVA3LAB.con;
import ds.Category;
import ds.Expense;
import ds.PersonalFinance;
import static java.awt.image.ImageObserver.WIDTH;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;


/**
 *
 * @author Lenovo
 */
public class Islaidu extends javax.swing.JDialog {
PersonalFinance a = null;
Category categ = null;
Expense expe=null;
    /**
     * Creates new form Islaidu
     */
    public Islaidu(java.awt.Frame parent, boolean modal,PersonalFinance a) {
        super(parent, modal);
    try {
        this.a=a;
        initComponents();
        String sql = "SELECT KATEGORIJOS, DESCR FROM APP.PS";
        ResultSet rsl = con.getback(sql);
        ResultSetMetaData rsmd = rsl.getMetaData();
        int columnsNumber = rsmd.getPrecision(WIDTH);
        String [] mas = new String [columnsNumber];
        int i=0;
        
         while(rsl.next()) {
            mas[i]=rsl.getString("KATEGORIJOS");
            i++;
        }
        cat.setModel(new javax.swing.DefaultComboBoxModel<>(mas));
    } catch (SQLException ex) {
        Logger.getLogger(Islaidu.class.getName()).log(Level.SEVERE, null, ex);
    }
       
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cat = new javax.swing.JComboBox<>();
        chekque = new javax.swing.JTextField();
        date = new javax.swing.JTextField();
        comment = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        expense = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Expenses");

        jLabel1.setText("Category:");

        jLabel2.setText("Chekque");

        jLabel3.setText("Date:");

        jLabel4.setText("Comment:");

        cat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                catActionPerformed(evt);
            }
        });

        chekque.setText("#323a23");

        date.setText("2020-04-08");
        date.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateActionPerformed(evt);
            }
        });

        comment.setText("coffe");
        comment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                commentActionPerformed(evt);
            }
        });

        jButton1.setText("save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        expense.setText("3.2");
        expense.setToolTipText("");

        jLabel5.setText("Expense:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chekque)
                            .addComponent(cat, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(date, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
                            .addComponent(comment)
                            .addComponent(expense))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cat))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(chekque))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(date))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(comment))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(expense, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void commentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_commentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_commentActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
                                       
              try{
            String checque = this.chekque.getText();
           String value = (String)cat.getSelectedItem();
            String com = this.comment.getText();
            String datele = this.date.getText();
           // Date date1=new SimpleDateFormat("YYYY-MM-DD").parse(datele);
            
            DateFormat formatter = new SimpleDateFormat("yyyy-MM-dd");
Date myDate = formatter.parse(datele);
java.sql.Date sqlDate = new java.sql.Date(myDate.getTime());
            
            String ex = this.expense.getText();
            Double exp = Double.parseDouble(ex);
           // String strl = "REPLACE APP.PS SET ISLAIDOS=ISLAIDOS+?, CEKIS=?, KOMENTARAS=?, DATA=? WHERE KATEGORIJOS = ?";
        //  String strl1 = "INSERT INTO APP.PS (ISLAIDOS,CEKIS,KOMENTARAS,DATA) VALUES(? , ? , ? , ?) ON DUPLICATE KEY UPDATE KATEGORIJOS = ?";
           // String str = "UPDATE APP.PS SET ISLAIDOS = ISLAIDOS + ?, CEKIS = ?, KOMENTARAS = ?, DATA = ? WHERE KATEGORIJOS = ?";
        //   String sudas = "INSERT INTO APP.PS (ISLAIDOS,CEKIS,KOMENTARAS,DATA) VALUES (? , ? , ? , ?)";
           String strl1 = "INSERT INTO APP.PS (ISLAIDOS,CEKIS,KOMENTARAS,DATA) VALUES(? , ? , ? , ?)";
             con.addexp(strl1 ,exp, checque, com, sqlDate);
           // expe = a.gautikategorija(value).addExpence(exp, checque, com, date1);
               this.dispose();
            }catch(Exception e){
                JOptionPane.showMessageDialog(this,"Wrong input");
            }
           
    }//GEN-LAST:event_jButton1ActionPerformed

    private void catActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_catActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_catActionPerformed

    private void dateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dateActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cat;
    private javax.swing.JTextField chekque;
    private javax.swing.JTextField comment;
    private javax.swing.JTextField date;
    private javax.swing.JTextField expense;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
