/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import ds.Category;
import ds.Expense;
import ds.Income;
import ds.PersonalFinance;
import static java.awt.image.ImageObserver.WIDTH;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;
import java2lab.Connectiona;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.filechooser.FileNameExtensionFilter;
import static jdk.nashorn.internal.objects.NativeMath.round;

/**
 *
 * @author Lenovo
 */
public class JAVA3LAB extends javax.swing.JFrame {
  PersonalFinance pf =new PersonalFinance();
   catinput kiv;
  Catsar cts = new Catsar(pf);
   Islaidusar is = new Islaidusar(pf);
   pajamusar paj = new pajamusar(pf);
  Category cat;
  
  static Connectiona con = new Connectiona();
  
  
 
  Income in=null;
  Expense ex= null;
    /**
     * Creates new form JAVA3LAB
     */
    public JAVA3LAB() throws SQLException {
       
        initComponents();
         lentele();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        balansinis = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Personal finance system");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Labas", "ka", "tu", "?", null},
                {"", "", null, "", null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Category", "Description", "Expense", "Income", "Sum"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        balansinis.setEditable(false);
        balansinis.setText("Overall balance:");
        balansinis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                balansinisActionPerformed(evt);
            }
        });

        jMenu1.setText("File");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("Open existing system");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem3.setText("Save files");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);
        jMenu1.add(jSeparator1);

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem4.setText("Exit");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Category");

        jMenuItem5.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem5.setText("New category");
        jMenuItem5.setActionCommand("");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem5);

        jMenuItem6.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem6.setText("Show category list");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem6);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setText("Delete or edit category");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Finance");

        jMenuItem7.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem7.setText("Add expenses");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem7);

        jMenuItem9.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem9.setText("Add income");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem9);

        jMenuItem10.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem10.setText("Expenses");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem10);

        jMenuItem11.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem11.setText("Incomes");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem11);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("About");

        jMenuItem8.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem8.setText("General usage");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem8);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 477, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(346, 346, 346)
                        .addComponent(balansinis)))
                .addGap(37, 37, 37))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                .addGap(39, 39, 39)
                .addComponent(balansinis)
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
       System.exit(0);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
       
             JFileChooser langas = new JFileChooser();
              langas.setFileFilter (new FileNameExtensionFilter("pf filas", "pf"));
             int rez = langas.showOpenDialog(null);
             if(rez== JFileChooser.APPROVE_OPTION){
             File failas = langas.getSelectedFile();
                     try{
            ObjectInputStream out = new ObjectInputStream(new FileInputStream(failas));
            pf = (PersonalFinance) out.readObject(); 
            out.close();
        } catch (Exception e) {
JOptionPane.showMessageDialog(this, "Error while reading file ", "Error" ,  JOptionPane.ERROR_MESSAGE);
        } 
                     
                     
         }
               
             
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
      try {
          Islaidu isl=new Islaidu(this,true,pf);
          String sql = "SELECT KATEGORIJOS, DESCR FROM APP.PS";
          ResultSet rsl = con.getback(sql);
          ResultSetMetaData rsmd = rsl.getMetaData();
    int b=0;
          int columnsNumber = rsmd.getColumnCount();
         while(rsl.next()){
          b++;
      }
                
          if(b>0){
              isl = new Islaidu(this,true,pf);
              isl.setVisible(true);
          }else{
              JOptionPane.showMessageDialog(this, "Add Category");
              
          }
          lentele();
          is.atnaujintilentele5();
          is.repaint();
      } catch (SQLException ex) {
          Logger.getLogger(JAVA3LAB.class.getName()).log(Level.SEVERE, null, ex);
      }
    }//GEN-LAST:event_jMenuItem7ActionPerformed
    
    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        JFileChooser langas = new JFileChooser();
        langas.setFileFilter (new FileNameExtensionFilter("pf filas", "pf"));
             int rez = langas.showSaveDialog(this);
               if(rez== JFileChooser.APPROVE_OPTION){
        try{
           ObjectOutputStream out = new ObjectOutputStream(new FileOutputStream(langas.getSelectedFile()));
           out.writeObject(pf);
            out.close();
        } catch (Exception e){
            JOptionPane.showMessageDialog(this, "Error while saving file ", "Error" ,  JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jMenuItem3ActionPerformed
 }
    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:// new cat
     kiv = new catinput(this,true,pf);
     cat = kiv.cat;
        kiv.setVisible(true);
         cts.atnaujintilentele();
        
      try {
          lentele();
      } catch (SQLException ex) {
          Logger.getLogger(JAVA3LAB.class.getName()).log(Level.SEVERE, null, ex);
      }
           cts.repaint();
          
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        cts.atnaujintilentele();
        cts.setVisible(true);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
      JOptionPane.showMessageDialog(this,"This is a basic program for controlling your personal finance.\n"
              + "It contains Categories,expenses,includes,and overall balance.");
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
      try {
          Pajamu paja=new Pajamu(this,true,pf);
          String sql = "SELECT KATEGORIJOS, DESCR FROM APP.PS";
          ResultSet rsl = con.getback(sql);
          ResultSetMetaData rsmd = rsl.getMetaData();
          int columnsNumber = rsmd.getColumnCount();
          int b=0;
            while(rsl.next()){
          b++;
      }
          if(b>0){
              paja = new Pajamu(this,true,pf);
              paja.setVisible(true);
          }else{
              JOptionPane.showMessageDialog(this, "Add Category");
              
          }
          lentele();
          paj.atnaujintilentele3();
          paj.repaint();
      } catch (SQLException ex) {
          Logger.getLogger(JAVA3LAB.class.getName()).log(Level.SEVERE, null, ex);
      }
      
    }//GEN-LAST:event_jMenuItem9ActionPerformed
    private void balansinisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_balansinisActionPerformed
         
            
    }//GEN-LAST:event_balansinisActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
          // TODO add your handling code here:// new cat
    Delcat ct = new Delcat(this,true,pf);
        ct.setVisible(true);
         cts.atnaujintilentele();
      try {
          lentele();
      } catch (SQLException ex) {
          Logger.getLogger(JAVA3LAB.class.getName()).log(Level.SEVERE, null, ex);
      }
           cts.repaint();
          
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
      is.atnaujintilentele5();
       is.setVisible(true);
     
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
      paj.atnaujintilentele3();
     paj.setVisible(true);
    }//GEN-LAST:event_jMenuItem11ActionPerformed
   
    public void lentele() throws SQLException{
      
       String sql = "SELECT * FROM APP.PS";
        ResultSet rsl = con.getback(sql);
        ResultSetMetaData rsmd = rsl.getMetaData();
        int columnsNumber = rsmd.getPrecision(WIDTH);
          
    String [][] mas = new String [columnsNumber][5];
    int i = 0;
    Double plus = 0.0;
    Double minus = 0.0;
    Double plumin = 0.0;
    
    
       while(rsl.next()) {
        int j=0;
        mas[i][0] = rsl.getString("KATEGORIJOS");   
        mas[i][1] = rsl.getString("DESCR");   
          mas[i][2] = rsl.getString("ISLAIDOS");  
           double[] sume = {0.00};
            double[] pajame = {0.00};
         sume[j]+=rsl.getDouble("ISLAIDOS");  
             minus+= rsl.getDouble("ISLAIDOS");  
             
            mas[i][3] = rsl.getString("PAJAMOS"); 
            
            pajame[j]+=rsl.getDouble("PAJAMOS");  
               plus+=rsl.getDouble("PAJAMOS");  
 
    
             double[] ben = {0.00};
        ben[j]=pajame[j]-sume[j];
         round(ben,2);
           mas[i][4] =Arrays.toString(ben);
        
            i++;
            plumin =plus-minus;
            round(plumin,2);
                    
    }
    
          jTable1.setModel(new javax.swing.table.DefaultTableModel(
           mas,
            new String [] {
                "Category", "Description", "Expene", "Income", "Sum"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
         
        balansinis.setText("Overall balanse: "+plumin);
          
   
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JAVA3LAB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JAVA3LAB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JAVA3LAB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JAVA3LAB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new JAVA3LAB().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(JAVA3LAB.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField balansinis;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
