/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package UI;

import static UI.JAVA3LAB.con;
import ds.Category;
import ds.PersonalFinance;
import static java.awt.image.ImageObserver.WIDTH;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Lenovo
 */
public class pajamusar extends javax.swing.JFrame {
PersonalFinance a = null;
    /** Creates new form pajamusar */
    public pajamusar(PersonalFinance b) {
         a=b;
        initComponents();
         atnaujintilentele3();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jList1.setToolTipText("");
        jScrollPane1.setViewportView(jList1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 322, Short.MAX_VALUE)
                .addGap(64, 64, 64))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                .addGap(50, 50, 50))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

     public void atnaujintilentele3(){
    try {
        String sql = "SELECT PAJAMOS FROM APP.PS";
        ResultSet rsl = con.getback(sql);
        ResultSetMetaData rsmd = rsl.getMetaData();
        int columnsNumber = rsmd.getPrecision(WIDTH);
        String [] mas = new String [columnsNumber];
     
        int i = 0;
        while(rsl.next()) {
            mas[i] = rsl.getString("PAJAMOS");   
            i++;
        }
        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = mas;
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
    } catch (SQLException ex) {
        Logger.getLogger(pajamusar.class.getName()).log(Level.SEVERE, null, ex);
    }
     }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

}
